apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: git-arc
  namespace: cluster-mgmt
spec:
  # interval: 1m
  url: https://github.com/zaidmohd/hello_arc
  ref:
    branch: master
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: cluster-mgmt
spec:
  # The interval at which to reconcile the Helm release
  interval: 10m
  releaseName: nginx-ingress
  chart:
    spec:
      # The path of the chart relative to the repository root
      chart: charts/nginx-ingress
      # The reference to the GitRepository
      sourceRef:
        kind: GitRepository
        name: git-arc
  values:
    image:
      repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
      tag: "0.32.0"
    replicaCount: 3