apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: hello-arc
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 1m
  releaseName: nginx-ingress
  chart:
    spec:
      chart: charts/nginx-ingress
  values:
    image:
      repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
      tag: "0.33.0"
    replicaCount: 3

# apiVersion: source.toolkit.fluxcd.io/v1beta1
# kind: HelmRepository
# metadata:
#   name: bitnami
#   namespace: hello-arc
# spec:
#   interval: 30m
#   url: https://charts.bitnami.com/bitnami
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: nginx
#   namespace: hello-arc
# spec:
#   releaseName: nginx-ingress-controller
#   chart:
#     spec:
#       chart: nginx-ingress-controller
#       sourceRef:
#         kind: HelmRepository
#         name: bitnami
#         namespace: hello-arc
#       version: "5.6.14"
#   interval: 1h0m0s
#   install:
#     remediation:
#       retries: 3
#   # Default values
#   # https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values.yaml
#   values:
#     service:
#       type: LoadBalancer